---
title: "Data Process"
author: "Jacky"
date: "2023-09-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# package

```{r}

library(dplyr)
library(tibble)
library(ggplot2)

library(caret)
library(themis)

# 家
# source(file = "CountyToRegion.R", encoding = "utf-8")
# source(file = "NearZeroVariance_Tbl.R", encoding = "utf-8")
# 
# projAbs <- rprojroot::is_rstudio_project$find_file()
# source(
#   file = file.path(projAbs, "ml_fun", "varNameConverter.R"),
#   encoding = "utf-8"
# )
# 
# rm(projAbs)

# 公司
source(file = "Function/NearZeroVariance_Tbl.R", encoding = "utf-8")
source(file = "Function/VarNameConverter.R", encoding = "utf-8")
source(file = "Function/CountyToRegion.R", encoding = "utf-8")

```


# import data

```{r}

load("mData.rda")

# 變造因子
lst_mData$Factor$營業縣市 <- sapply(lst_mData$Factor$營業縣市, county2region)
lst_mData$Factor$資本額 <- log(ifelse(lst_mData$Factor$資本額 == 0, 1, lst_mData$Factor$資本額))

```

排除同業者稽查？


# process data

## 合併資料

```{r}

tbl_mData1 <- lst_mData$Factor %>% 
  left_join(x = ., y = lst_mData$ExpCase, by = join_by(稽查事件編號)) %>% 
  select(!c("現場稽查描述（原始）", "現場稽查描述（節錄）")) %>% 
  mutate(
    `是否逾期` = as.factor(ifelse(is.na(逾期案件), "N", "Y"))
  ) %>% 
  select(!逾期案件)

# 前台逾期食品案件
webExp <- intersect(tbl_mData1$稽查事件編號, lst_mData$WebExpCase$稽查序號)

for (i in 1:nrow(tbl_mData1)) {
  
  if (tbl_mData1$稽查事件編號[[i]] %in% webExp) {
    tbl_mData1$是否逾期[[i]] <- "Y"
  }
}

rm(i, webExp)

```

## NZV

```{r}

# 以訓練組計算次數比率
tbl_train1 <- tbl_mData1 %>% filter(Group == "train")
cutPt <- {tbl_train1 %>% filter(是否逾期 == "N") %>% nrow()} / 
  {tbl_train1 %>% filter(是否逾期 == "Y") %>% nrow()}

# nzv因子
tbl_nzv <- tbl_train1 %>% nzvTbl(excluCol = c("稽查事件編號", "Group", "是否逾期"), cutPt = cutPt)
# write.csv(tbl_nzv, file = "nzv.csv", row.names = F)

# 刪除nzv因子
col_nzv <- tbl_nzv %>% 
  filter(NearZeroVariance) %>% 
  {.[[1]]}
tbl_mData2 <- tbl_mData1 %>% select(!col_nzv)

rm(cutPt, tbl_train1, tbl_nzv, col_nzv)
```

## Numeric

```{r}

# tbl_mData2 %>%
#   ggplot(data = ., mapping = aes(x = 資本額)) +
#   geom_histogram(bins = 90)

```

```{r}

tbl_mData <- tibble(
  `訓or測` = as.factor(tbl_mData2$Group),
  `稽查事件編號` = tbl_mData2$稽查事件編號, 
  `ln資本額` = tbl_mData2$資本額, 
  `餐飲業次業別數` = tbl_mData2$餐飲業次業別數, 
  `標章分數` = tbl_mData2$標章分數
)

# tbl_mData %>%
#   ggplot(data = ., mapping = aes(x = ln資本額)) +
#   geom_histogram(bins = 90)

```

## Factor

```{r}

tbl_mData3 <- tbl_mData2 %>% 
  select(!c("Group", "稽查事件編號", "資本額", "餐飲業次業別數", "標章分數"))

for (i in seq_along(tbl_mData3)) {
  tbl_mData3[[i]] <- as.factor(tbl_mData3[[i]])
}

remove(i)
```

```{r}

tbl_mData <- cbind(tbl_mData, tbl_mData3)

```

## 更改欄位名稱

```{r}

nOri <- names(tbl_mData)

tbl_mData <- varNameConverter(
  tbl_mData, "是否逾期", c("訓or測", "稽查事件編號")
)

nX <- names(tbl_mData)

tbl_vName <- tibble(
  Origin = nOri, 
  X = nX
)

```


# train, test

```{r}

tbl_train <- tbl_mData %>% 
  filter(訓or測 == "train") %>% 
  select(!訓or測)

tbl_test <- tbl_mData %>% 
  filter(訓or測 == "test") %>% 
  select(!訓or測)

```

```{r}

lst_ttData <- list(
  train = tbl_train, 
  test = tbl_test, 
  vName = tbl_vName
)

# save(lst_ttData, file = "ttData.Rda")

```







