---
title: "Machine Learning"
author: "Jacky"
date: "2023-09-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# package

```{r}

library(tibble)
library(dplyr)
library(ggplot2)
library(stringr)

library(themis)
# library(MASS)    # 命名衝突：select()

# library(DescTools)
# library(BMA)

```


# import data

```{r}

load(file = "ttData.Rda")

```

```{r}

# lst_ttData$test %>%
#   filter(Y == "Y")

```

```{r}

nrow(lst_ttData$train[lst_ttData$train$Y == "Y", ]) / nrow(lst_ttData$train)
nrow(lst_ttData$test[lst_ttData$test$Y == "Y", ]) / nrow(lst_ttData$test)

```


# model building

```{r}

# SMOTE
set.seed(4)

train_sm <- lst_ttData$train %>%
  select(!稽查事件編號) %>%
  smotenc(
    df = ., var = "Y",
    k = 5,
    over_ratio = 3/7    # minority/majority
  )

```

```{r}

lgsMdl_0 <- glm(
  Y ~ ., data = train_sm, 
  family = "binomial"
)

# feature selection
lgsMdl_sBIC <- MASS::stepAIC(lgsMdl_0, k = log(nrow(train_sm)))

# final model
lgsMdl <- glm(
  formula = lgsMdl_sBIC$formula, data = train_sm, 
  family = binomial()
)

```


# prediction

```{r}

rsl_prob <- predict(lgsMdl, newdata = lst_ttData$test, type = "response")

# 切幾家？
tbl_rsl <- tibble(
  `實際` = lst_ttData$test$Y, 
  `預測機率` = rsl_prob, 
  `預測機率排序` = rank(-rsl_prob, ties.method = "min")
) %>% 
  mutate(
    `預測` = {ifelse(預測機率排序 <= 200, "Y", "N") %>% as.factor()}
  )

```

```{r}

# c.f. matrix
table(Predicted = tbl_rsl$預測, Actual = tbl_rsl$實際)

```

```{r}

lgsMdl_sBIC$anova
lst_ttData$vName

```

```{r}

# prob distr.
tbl_rsl %>% 
  ggplot(mapping = aes(x = 預測機率)) + 
  geom_histogram(bins = 500)

```





# DescTools

```{r}

# PseudoR2(mdl_lgs, which = "all")

```


# BMA

```{r}

# lgsMdl_eva <- bic.glm(
#   f = Y~., data = lst_ttData$train_sm, 
#   glm.family = "binomial"
# )
# 
# n <- lgsMdl_eva$label[[1]] %>%
#   str_split_1(",") %>%
#   str_extract("X[0-9]{2}")
# 
# trainD <- lst_ttData$train_sm[, c(n, "Y")]
# testD <- lst_ttData$test[, c(n, "Y")]

```


















