---
title: "data process"
author: "Jacky"
date: "2021/1/5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# package

```{r}

library(readxl)
library(SOAR)

# tidyverse
library(readr)
library(dplyr)
library(stringr)
library(purrr)
library(lubridate)

# my function
projAbs <- rprojroot::is_rstudio_project$find_file()
source(file = file.path(projAbs, "ml_fun", "varNameConverter.R"))
rm(projAbs)

```



# data import

```{r}
load(file = "rda_mdlData_veg/vegetable_mdlData_raw.Rda")
```



# data processing

## 刪除非變數

```{r}

mdlData_pro <- mdlData_raw[
  setdiff(
    names(mdlData_raw), c("簽審核准許可文件編號", "報單項次", "檢驗不合格")
  )
]

```

## 變數class轉factor

```{r}

for (i in seq_along(mdlData_pro)) {
  
  if(
    str_detect(names(mdlData_pro)[[i]], pattern = "受理日期")
  ){
    mdlData_pro[[i]] <- lubridate::ymd(mdlData_pro[[i]])
  } else{
    mdlData_pro[[i]] <- as.factor(mdlData_pro[[i]])
  }
}

rm(i)

```

## 中文level轉英文

```{r}

# 找出含中文字之level
list_varLevel <- map(mdlData_pro, ~levels(.x))

map(
  list_varLevel, ~{str_detect(.x, "[\u4E00-\u9FFF]") %>% sum()}
) %>% 
  unlist(use.names = F) %>% 
  {ifelse(. > 0, yes = T, no = F)} %>% 
  which()

# 中文level轉英文
levels(mdlData_pro[[2]]) <- c("1", "0")
levels(mdlData_pro[[8]]) <- c("Kaohsiung", "Keelung", "Taichung", "Taipei")
levels(mdlData_pro[[10]]) <- c("air", "ship")
levels(mdlData_pro[[13]]) <- c("Middle", "North", "South", "Null")
levels(mdlData_pro[[15]]) <- c("0", "1", "Null")

rm(list_varLevel)

```

## 變數名稱轉代數

```{r}

mdlData_pro_nb <- mdlData_pro %>% 
  select(-contains("黑名單"))

mdlData_pro_bp <- mdlData_pro %>% 
  select(-黑名單號列, -黑名單生產國, -黑名單進口商, -`黑名單產品(舊)`)

mdlData_pro_bg <- mdlData_pro %>% 
  select(-黑名單產品, -黑名單生產國, -黑名單進口商, -`黑名單產品(舊)`)

mdlData_pro_bgOld <- mdlData_pro %>% 
  select(-黑名單產品, -黑名單號列, -黑名單生產國, -黑名單進口商)

mdlData_pro_bc <- mdlData_pro %>% 
  select(-黑名單產品, -黑名單號列, -黑名單進口商, -`黑名單產品(舊)`)

mdlData_pro_bi <- mdlData_pro %>% 
  select(-黑名單產品, -黑名單號列, -黑名單生產國, -`黑名單產品(舊)`)

```

```{r}

mdlData_pro_nb <- varnameConverter(
  data = mdlData_pro_nb, dep = "批檢驗結果(除去標示因素)", exclu = "受理日期"
)

mdlData_pro_bp <- varnameConverter(
  data = mdlData_pro_bp, dep = "批檢驗結果(除去標示因素)", exclu = "受理日期"
)

mdlData_pro_bg <- varnameConverter(
  data = mdlData_pro_bg, dep = "批檢驗結果(除去標示因素)", exclu = "受理日期"
)

mdlData_pro_bgOld <- varnameConverter(
  data = mdlData_pro_bgOld, dep = "批檢驗結果(除去標示因素)", exclu = "受理日期"
)

mdlData_pro_bi <- varnameConverter(
  data = mdlData_pro_bi, dep = "批檢驗結果(除去標示因素)", exclu = "受理日期"
)

mdlData_pro_bc <- varnameConverter(
  data = mdlData_pro_bc, dep = "批檢驗結果(除去標示因素)", exclu = "受理日期"
)

```

```{r}
# save(mdlData_pro_nb, file = "rda_mdlData_veg/veg_mdlData_pro_nb.Rda")
# save(mdlData_pro_bp, file = "rda_mdlData_veg/veg_mdlData_pro_bp.Rda")
# save(mdlData_pro_bg, file = "rda_mdlData_veg/veg_mdlData_pro_bg.Rda")
# save(mdlData_pro_bgOld, file = "rda_mdlData_veg/veg_mdlData_pro_bgOld.Rda")
# save(mdlData_pro_bi, file = "rda_mdlData_veg/veg_mdlData_pro_bi.Rda")
# save(mdlData_pro_bc, file = "rda_mdlData_veg/veg_mdlData_pro_bc.Rda")
```






