---
title: "Machine Learning"
author: "Jacky Wang"
date: "2024-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# package

```{r}

library(tibble)
library(dplyr)
library(ggplot2)

library(themis)
library(ROCR)

```


# import data

```{r}
load(file = "ttData.rda")

lst_ttData$train$Y <- as.factor(lst_ttData$train$Y)
lst_ttData$test$Y <- as.factor(lst_ttData$test$Y)
```

```{r}

nrow(lst_ttData$train[lst_ttData$train$Y == "0", ]) / nrow(lst_ttData$train)
nrow(lst_ttData$test[lst_ttData$test$Y == "0", ]) / nrow(lst_ttData$test)

# lst_ttData$test[1:3] %>%
#   group_by(稽查年度, Y) %>%
#   summarise(
#     家數 = n_distinct(業者編號)
#   ) %>%
#   ungroup() %>%
#   {.[[3]]} %>% sum()

```

```{r}
# write.csv(lst_ttData$nzv, file = "nzv.csv", row.names = F)
```


# SMOTE

```{r}

set.seed(4)

train_sm <- lst_ttData$train[-c(1, 2)] %>% 
  smotenc(
    df = ., var = "Y",
    k = 5,
    over_ratio = 1/9    # minority/majority
  )

```


# modeling

```{r}

# a <- Sys.time()

lgsMdl_0 <- glm(
  Y ~ ., data = train_sm, 
  family = "binomial"
)

# feature selection
lgsMdl_sBIC <- MASS::stepAIC(
  lgsMdl_0, 
  k = log(nrow(train_sm)), 
  direction = "backward"
)

# b <- Sys.time()
# c <- difftime(b, a, units = "sec") %>% floor() %>% as.numeric()
# stringr::str_glue("耗時約 {c %/% 60} 分 {c %% 60} 秒")    # 約6分，考慮用glmnet()（lasso regression）
# 
# rm(a, b, c)
```

```{r}

lgsMdl_sBIC$anova

lst_ttData$vName %>%
  filter(
    !(X %in% names(lgsMdl_sBIC$model))
  )

rm(train_sm, lgsMdl_0)
```


# prediction

```{r}

rsl_prob <- predict(lgsMdl_sBIC, newdata = lst_ttData$test, type = "response")

# 切幾家？
tbl_rsl <- tibble(
  `實際` = lst_ttData$test$Y, 
  `預測機率` = rsl_prob, 
  `預測機率排序` = rank(-rsl_prob, ties.method = "min")
) %>% 
  mutate(
    `預測` = {ifelse(預測機率排序 < 12714*0.2, "1", "0") %>% as.factor()}
  )

```

```{r}

# c.f. matrix
table(Predicted = tbl_rsl$預測, Actual = tbl_rsl$實際)

```

```{r}

pred <- prediction(tbl_rsl$預測機率, tbl_rsl$實際)
perf <- performance(pred, measure = "tpr", x.measure = "fpr")
plot(perf, col=rainbow(10))

pred_auc <- performance(pred, measure = "auc")
pred_auc@y.values[[1]]

```

```{r}

tbl_ROC <- tibble(
  FPR = perf@x.values[[1]], 
  TPR = perf@y.values[[1]]
)

tbl_ROC %>% 
  ggplot(aes(x = FPR, y = TPR)) + 
  geom_abline(
    intercept = 0, slope = 1, 
    color = "grey", linetype = "dashed"
  ) + 
  geom_line() + 
  theme_bw() + 
  coord_fixed()



```




```{r}

# 預測機率分佈
tbl_rsl %>% 
  ggplot(aes(x = 預測機率)) + 
  geom_histogram(bins = 100)

```











